#!/bin/sh

apt update
apt install -y python3-tk python3-pip
pip install -r requirements.txt

python disco.py --n_batches 0 --text_prompts '{"0": ["Space panorama of celestial space station, cosmic, photorealistic materials, beeple behance"]}' --steps 250 --width_height '[1920, 1088]'
