RN101: false
RN50: true
RN50x16: false
RN50x4: false
RN50x64: false
ViTB16: true
ViTB32: true
ViTL14: false
ViTL14_336: true
batch_name: prompt_salad
prompt_salad: true
prompt_salad_template: a {adjectives} and {adjectives} {locations} of {of_something}, art by {artists}
prompt_salad_amount: 20